apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin-dev
config:
  origins:
  - '*'
  credentials: true
  preflight_continue: false
plugin: cors

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: pre-kong-plugin
  labels:
    global: 'true'
disabled: false
config:
  functions:
  - |
    local request_method = kong.request.get_method()
    local request_custom_header = kong.request.get_header('X-TENANT-ID')
    if request_method ~= 'OPTIONS' and request_custom_header ~= 'hellio' then
    return kong.response.exit(404)
    end
plugin: pre-function

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    konghq.com/plugins: cors-plugin-dev, pre-kong-plugin
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /hello
        pathType: ImplementationSpecific
        backend:
          service:
            name: hello-service
            port:
              number: 5000